-- =============================================
-- SUPABASE SCHEMA: Trini Carnival Rentals
-- Paste this ENTIRE script into your Supabase SQL Editor and click "Run"
-- =============================================

-- 1. Create properties table
CREATE TABLE properties (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  tagline TEXT,
  location TEXT,
  bedrooms INTEGER,
  bathrooms REAL,
  capacity INTEGER,
  "bedroomDetail" TEXT,
  "priceTTD" TEXT,
  "priceUSD" TEXT,
  badge TEXT,
  pricing_note TEXT,
  image TEXT,
  gallery JSONB DEFAULT '[]',
  description TEXT,
  "descriptionLong" TEXT,
  amenities JSONB DEFAULT '[]',
  "bedroomLayout" JSONB
);

-- 2. Create bookings table
CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "propertyId" TEXT REFERENCES properties(id),
  "checkIn" TEXT,
  "checkOut" TEXT,
  "firstName" TEXT,
  "lastName" TEXT,
  email TEXT,
  phone TEXT,
  guests INTEGER,
  message TEXT,
  status TEXT DEFAULT 'Pending',
  "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Enable Row Level Security
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies (Open for MVP)
CREATE POLICY "Allow public read on properties" ON properties FOR SELECT USING (true);
CREATE POLICY "Allow public insert on bookings" ON bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read on bookings" ON bookings FOR SELECT USING (true);
CREATE POLICY "Allow public update on bookings" ON bookings FOR UPDATE USING (true);

-- 5. Seed all properties
INSERT INTO properties (id, name, tagline, location, bedrooms, bathrooms, capacity, "bedroomDetail", "priceTTD", "priceUSD", badge, pricing_note, image, gallery, description, "descriptionLong", amenities, "bedroomLayout") VALUES
('acacia', 'Acacia', 'Modern Masterpiece | 4 Bed | 4 Bath', 'Mount Irvine', 4, 4, 8, '4 Bedrooms + A Private Studio', '$3200 - $3500 TTD', '$470 - $515 USD', 'Featured', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80',
 '["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200","https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200","https://images.unsplash.com/photo-1600585154526-990dcea4db0d?w=1200","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200","https://images.unsplash.com/photo-1542314831-c6a4d14b2d18?w=1200","https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200","https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200","https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200","https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200"]',
 'Acacia is a minimalist architectural masterwork.', 'Designed for the sophisticated traveler, Acacia features floor-to-ceiling glass and a stunning infinity pool.',
 '["WIFI","POOL","AC","KITCHEN","GATED"]', null),

('amber', 'Amber', 'Tropical Oasis | 3 Bed | 3 Bath', 'Mount Irvine', 3, 4.5, 8, '3 Bedrooms + A Loft', '$2800 - $3000 TTD', '$412 - $441 USD', 'Popular', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
 '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200","https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=1200","https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200","https://images.unsplash.com/photo-1556912177-c54030639a61?w=1200","https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200","https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200","https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=1200","https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1200","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200"]',
 'A serene retreat overlooking Stone Haven Bay.', 'The Amber Estate offers dramatic sunset views and a private path to a secluded beach area.',
 '["FULLY AIRCONDITIONED","LINEN & TOWELS","EQUIPPED KITCHEN","WIFI","PRIVATE POOL","BBQ PIT","SECURE PARKING"]', null),

('arara', 'Arara', 'Garden Sanctuary', 'Black Rock', 5, 5, 10, '5 Bedrooms + Media Room', '$3500 - $3800 TTD', '$515 - $560 USD', null, null, 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600',
 '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200","https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200","https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=1200","https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200","https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200","https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=1200","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200","https://images.unsplash.com/photo-1600585154524-2813983946cc?w=1200"]',
 'Arara is nestled in a lush tropical garden.', 'Located within the picturesque, gated compound of Samaan Grove, perfect for leisurely strolls or fitness enthusiasts. This fully airconditioned four-bedroom villa sleeps 12 persons and has a pull-out sofa for extra guests. The pool area contains a pool bar, outdoor cooking facilities and bathroom, making this villa perfect for pool side entertainment.',
 '["FULLY AIRCONDITIONED","LINEN & TOWELS","FULLY EQUIPPED KITCHEN","POOL BAR WITH COOKING FACILITIES & BATHROOM","3 FLAT SCREEN TVS","LAUNDRY ROOM","BBQ PIT","WIFI","PRIVATE POOL","PARKING","WITHIN A SECURE GATED COMPOUND"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"","bed":"1 Queen Bed"},{"title":"Bedroom 3","type":"Ensuite","bed":"2 Queen Beds"},{"title":"Bedroom 4","type":"Ensuite","bed":"2 Queen Beds"}]'),

('carnival-heights-villa', 'Carnival Heights Villa', 'Elevated luxury with panoramic views', 'St. Ann''s, Port of Spain', 4, 3, 8, '4 Bedrooms', '$2380 - $2880 TTD', '$350 - $400 USD', 'Popular', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
 '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80","https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80"]',
 'Perched in the hills of prestigious St. Ann''s, Carnival Heights Villa offers breathtaking panoramic views of Port of Spain and the Gulf of Paria. This spacious four-bedroom retreat features an open-plan living area that flows onto a wraparound terrace — perfect for watching the city come alive during Carnival season.',
 'Enjoy modern comforts including a fully equipped gourmet kitchen, high-speed WiFi, and a private plunge pool surrounded by lush tropical gardens. Located minutes from the Queen''s Park Savannah and all major Carnival fête venues, this villa is ideal for groups seeking both celebration and relaxation.',
 '["Private Pool","WiFi","Air Conditioning","Full Kitchen","Parking","Washing Machine","Smart TV","Security System","Terrace","BBQ Grill","Generator Backup","Daily Housekeeping"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 3","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 4","type":"Standard","bed":"1 Queen Bed"}]'),

('savannah-suite', 'The Savannah Suite', 'Steps from the heart of Carnival', 'Queen''s Park, Port of Spain', 2, 2, 4, '2 Bedrooms', '$1496 - $1996 TTD', '$220 - $270 USD', 'Central', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
 '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80","https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80"]',
 'Located directly on the Queen''s Park Savannah, this elegant two-bedroom suite puts you at the epicenter of Trinidad Carnival. Watch the Parade of Bands from your private balcony and walk to Dimanche Gras, Panorama, and all the action.',
 'The suite features high-end finishes throughout, with marble countertops, designer furnishings, and floor-to-ceiling windows that flood the space with natural light. Both bedrooms are en-suite with premium linens and blackout curtains — essential for recovering between fêtes.',
 '["WiFi","Air Conditioning","Full Kitchen","Parking","Smart TV","Balcony","Washer/Dryer","Iron & Board","Concierge Service","Security"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"}]'),

('maraval-retreat', 'Maraval Garden Retreat', 'Tropical tranquility with easy access', 'Maraval, Port of Spain', 3, 2, 6, '3 Bedrooms', '$1904 - $2404 TTD', '$280 - $330 USD', 'Quiet Escape', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
 '["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80","https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80"]',
 'Nestled in a quiet pocket of Maraval, this three-bedroom retreat is the perfect blend of tranquility and accessibility. Just a 10-minute drive from the Savannah, you can escape the Carnival buzz whenever you need to recharge.',
 'The property sits within a beautifully landscaped garden with mature tropical trees, offering a cool, shaded oasis. The open-plan kitchen is chef-friendly, and there''s a spacious entertainment area that''s ideal for hosting your own lime.',
 '["Private Garden","WiFi","Air Conditioning","Full Kitchen","Parking","Washing Machine","Smart TV","BBQ Grill","Security","Outdoor Dining"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 3","type":"Standard","bed":"1 Queen Bed"}]'),

('port-of-spain-penthouse', 'Waterfront Penthouse', 'Skyline views & modern luxury', 'Wrightson Road, Port of Spain', 3, 3, 6, '3 Bedrooms', '$2856 - $3356 TTD', '$420 - $470 USD', 'Premium', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
 '["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80","https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80"]',
 'This stunning top-floor penthouse overlooks the Port of Spain waterfront and the Gulf of Paria. Floor-to-ceiling glass walls offer uninterrupted views from every room, and the rooftop terrace is the ultimate vantage point for Carnival fireworks.',
 'Featuring three luxurious en-suite bedrooms, a state-of-the-art kitchen with premium appliances, and a separate entertainment lounge with surround sound, this penthouse defines modern Caribbean luxury. Building amenities include 24-hour security, a fitness center, and underground parking.',
 '["Rooftop Terrace","WiFi","Air Conditioning","Full Kitchen","Parking","Gym Access","Smart TV","Surround Sound","Concierge","Security","Elevator","Generator"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 3","type":"Standard","bed":"1 Queen Bed"}]'),

('cascade-cottage', 'Cascade Cottage', 'Charming hideaway in the valley', 'Cascade, Port of Spain', 2, 1, 4, '2 Bedrooms', '$1190 - $1690 TTD', '$175 - $225 USD', 'Value Pick', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
 '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80","https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80"]',
 'A charming two-bedroom cottage tucked away in the leafy Cascade valley. This cozy retreat offers excellent value without compromising on comfort or location — the Savannah is just a quick maxi taxi ride away.',
 'The cottage features warm wooden interiors, a private veranda with hammock, and a fully equipped kitchenette. The neighbourhood is friendly and safe, with local restaurants and doubles vendors within walking distance. Perfect for couples or a small group of friends.',
 '["WiFi","Air Conditioning","Kitchenette","Parking","Smart TV","Veranda","Hammock","Security","Ceiling Fans","Outdoor Seating"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"}]'),

('westmoorings-estate', 'Westmoorings Estate', 'Prestigious family compound', 'Westmoorings, Diego Martin', 5, 4, 12, '5 Bedrooms', '$3740 - $4240 TTD', '$550 - $600 USD', 'Exclusive', 'Inquire within for a quote', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
 '["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80","https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80","https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=80","https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600&q=80","https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=600&q=80","https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=600&q=80"]',
 'This expansive five-bedroom estate in exclusive Westmoorings is the ultimate group accommodation for Carnival. With a large private pool, entertainment pavilion, and manicured grounds, it''s designed for those who like to host and celebrate in grand style.',
 'The property features a master suite with walk-in closet and jacuzzi, four additional bedrooms, a professional-grade kitchen, and a separate staff quarters. Located in one of Trinidad''s most prestigious neighbourhoods with easy highway access to Port of Spain.',
 '["Private Pool","WiFi","Air Conditioning","Full Kitchen","Parking for 4","Washing Machine","Smart TV","Security System","Entertainment Pavilion","BBQ Area","Generator","Staff Quarters","Jacuzzi","Garden"]',
 '[{"title":"Bedroom 1","type":"Ensuite","bed":"1 Queen Bed"},{"title":"Bedroom 2","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 3","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 4","type":"Standard","bed":"1 Queen Bed"},{"title":"Bedroom 5","type":"Standard","bed":"1 Queen Bed"}]');
